name: Bug
description: Report a bug with detailed information to help us resolve it.
labels:
  - defect:bug

body:
  - type: textarea
    id: description
    attributes:
      label: ðŸž Summary
      description: >
        Describe the bug clearly and concisely. Include any relevant details
        about the environment or context in which the bug occurred.

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: ðŸ”„ Steps to Reproduce & Actual Result
      description: >
        List the exact steps to reproduce the bug.
        Be as detailed as possible by listing every action and/or input.
        Also, describe the actual result of following these steps.

  - type: textarea
    id: expected_result
    attributes:
      label: âœ… Expected Result
      description: >
        Describe what you expected to happen when following the steps.

  - type: dropdown
    id: platform
    attributes:
      label: ðŸ–¥ï¸ Platform
      description: Select the platform where the bug occurred.
      multiple: false
      options:
        - Mobile
        - Desktop
        - Browser Extension

  - type: input
    id: version
    attributes:
      label: ðŸ”¢ Version
      description: Enter the version number (e.g., v1.0.2) where the bug occurred.

  - type: textarea
    id: additional_info
    attributes:
      label: 'ðŸ“Ž Additional Information or Attachments'
      description: >
        Provide additional context with screenshots, videos or links.

  - type: input
    id: slack
    attributes:
      label: ðŸŽ¯ Slack
      description: Provide the URL for the Slack thread or channel.
