
name: Bug Report
description: Report a bug with detailed information to help us resolve it.
title: "Defect: Provide a concise and descriptive title"
labels: ["defect:bug"]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: "🐞 Bug Description"
      description: >
        Describe the bug clearly and concisely. Include any relevant details 
        about the environment or context in which the bug occurred.

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "🔄 Steps to Reproduce & Actual Result"
      description: >
        List the exact steps to reproduce the bug. Be as detailed as possible, 
        including specific actions, inputs, and settings. Also, describe the 
        actual result of following these steps.

  - type: textarea
    id: expected_result
    attributes:
      label: "✅ Expected Result"
      description: >
        Describe what you expected to happen when following the steps.
        
    - type: dropdown
    id: platform
    attributes:
      label: 🖥️ Platform
      description: Select the platform where the bug occurred.
      multiple: false
      options:
        - Mobile
        - Desktop
        - Browser Extension

  - type: input
    id: version
    attributes:
      label: 🔢 Version
      description: Enter the version number (e.g., v1.0.2) where the bug occurred.

  - type: textarea
    id: additional_info
    attributes:
      label: "📎 Additional Information or Attachments"
      description: >
        If relevant, provide additional context, screenshots, or links to 
        files or videos. Unfortunately, file uploads are not supported 
        directly in this form, but you can link to files hosted elsewhere.
