blank_issues_enabled: true
contact_links: []
issue_templates:
  - name: Standard Issue Template
    description: Use this template for creating detailed issues with predefined fields.
    file: issue-template.md
