name: Feature Request / Issue Report
description: Use this form to describe user stories, acceptance criteria, and reference materials.
title: 'Provide a descriptive title for your issue'
labels: []
assignees: []

body:
  - type: textarea
    id: overview
    attributes:
      label: ðŸ—’ï¸ Brief Overview / User Story
      description: >
        If this issue is user-related: Provide a brief summary or user story explaining the purpose of this issue. 
        Include the problem or opportunity being addressed and how it aligns with the project goals.

        If the issue is not user-related but for the product team, technical debt, or internal tooling: Describe the 
        purpose of the issue clearly. Include details such as its impact, why it's needed, and the specific team or 
        stakeholder that benefits from resolving it.

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: âœ… Acceptance Criteria
      description: >
        Define the conditions that must be met for this issue to be considered complete. Use clear, testable criteria.

  - type: input
    id: slack_link
    attributes:
      label: ðŸŽ¯ Slack Link
      description: Provide a Slack link formatted as `[label](URL)`. Example: `[Discussion](https://slack.com/example)`

  - type: input
    id: figma_link
    attributes:
      label: ðŸŽ¨ Figma Link
      description: Provide a Figma link formatted as `[label](URL)`. Example: `[Design Prototype](https://figma.com/example)`

  - type: input
    id: other_link
    attributes:
      label: ðŸ”— Other Reference Links
      description: Provide any other reference link formatted as `[label](URL)`. Example: `[Documentation](https://docs.com/example)`
