name: Format and Clean Issue Links

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  process-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Format and clean issue body
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract the issue number
          issue_number=${{ github.event.issue.number }}

          # Fetch the issue body using the GitHub CLI
          issue_body=$(gh api repos/${{ github.repository }}/issues/${issue_number} --jq '.body')

          # Debug: Output the raw issue body
          echo "Raw issue body:"
          echo "$issue_body"

          # Remove placeholder sections and '_No response_' explicitly
          new_body=$(echo "$issue_body" | sed -e '/### 🎨 Figma Link/,/^$/d' \
                                             -e '/### 🔗 Other Reference Links/,/^$/d' \
                                             -e 's/_No response_//g')

          # Debug: Output the new issue body
          echo "New issue body:"
          echo "$new_body"

          # Update the issue body via GitHub CLI
          gh api repos/${{ github.repository }}/issues/${issue_number} --method PATCH --field body="$new_body"
