
name: Format and Clean Issue Links

on:
  issues:
    types: [opened]

jobs:
  process-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Format and clean issue body
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract the issue number
          issue_number=${{ github.event.issue.number }}

          # Fetch the issue body using the GitHub CLI
          issue_body=$(gh api repos/${{ github.repository }}/issues/${issue_number} --jq '.body')

          # Debug: Output the raw issue body
          echo "Raw issue body:"
          echo "$issue_body"

          # Extract Slack, Figma, and Other Links
          slack=$(echo "$issue_body" | grep -i '🎯 Slack Link:' | sed 's/.*🎯 Slack Link: //')
          figma=$(echo "$issue_body" | grep -i '🎨 Figma Link:' | sed 's/.*🎨 Figma Link: //')
          other=$(echo "$issue_body" | grep -i '🔗 Other Reference Links:' | sed 's/.*🔗 Other Reference Links: //')

          # Rebuild the issue body, excluding empty fields
          new_body=$(echo "$issue_body" | sed -e "/🎯 Slack Link:.*/d"                                              -e "/🎨 Figma Link:.*/d"                                              -e "/🔗 Other Reference Links:.*/d")

          if [[ -n "$slack" ]]; then
            new_body="$new_body\n🎯 Slack Link: $slack"
          fi
          if [[ -n "$figma" ]]; then
            new_body="$new_body\n🎨 Figma Link: $figma"
          fi
          if [[ -n "$other" ]]; then
            new_body="$new_body\n🔗 Other Reference Links: $other"
          fi

          # Debug: Output the new issue body
          echo "New issue body:"
          echo "$new_body"

          # Update the issue body via GitHub CLI
          gh api repos/${{ github.repository }}/issues/${issue_number} --method PATCH --field body="$new_body"
